#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

. /root/.mysql_password

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to Cloudstack MySQL/phpMyAdmin Instance.
To keep this Cloudstack Instance secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), 443 (HTTPS), and 3306 (MySQL).

In a web browser, you can view:

 * phpMyAdmin: http://$myip/phpmyadmin
    Username: admin
    Password: $admin_mysql_pass

On the server:
 * The MySQL root password is saved in /root/.mysql_password
 * Certbot is preinstalled. Run it to configure HTTPS.
 * A default HTML page is located at /var/www/html/index.html and can be removed or replaced.



********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
