#!/bin/sh
#
# Configured as part of the Cloudstack Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to Cloudstack Docker Instamce.

To keep this Instance secure, the UFW firewall is enabled.

All ports are BLOCKED except 22 (SSH), 2375 (Docker) and 2376 (Docker).

* You can SSH to this Instance in a terminal as root: ssh root@$myip

* Docker is installed and configured per Docker's recommendations:
  https://docs.docker.com/install/linux/docker-ce/ubuntu/

* Docker Compose is installed and configured per Docker's recommendations:
  https://docs.docker.com/compose/install/#install-compose

********************************************************************************

To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
